#!/usr/bin/env bash

# Fix name resolution
tee /etc/resolv.conf > /dev/null <<EOF
# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 1.1.1.1
nameserver 172.16.2.2
nameserver 8.8.8.8
nameserver 10.248.16.30
nameserver 10.248.26.30
EOF

echo "✅ /etc/resolv.conf has been updated."

# Cleanup previous outputs
rm -f /app/questions.csv
rm -rf /app/jmeter.log
rm -rf /app/results.jtl

# Clone MathChat repository if missing
if [ ! -d "/app/MathChat" ]; then
    echo "📦 Cloning MathChat repo..."
    git clone https://github.com/Zhenwen-NLP/MathChat.git /app/MathChat
fi

# Run extraction if outputs are missing
if [ ! -f "/app/questions.csv" ]; then
    echo "  Running extract.py..."
    python /app/extract.py \
        --input "/app/MathChat/MathChat Benchmark/follow_up.jsonl" \
        --questions_output /app/questions.csv \
        --qa_output /app/qa.jsonl \
        --max 1500
fi

echo "✅ questions extracted."

# Start FastAPI server in the background
uvicorn server:app --host 0.0.0.0 --port 8000 --workers 1 &

# Wait for server to be ready
echo "⏳ Waiting for server to start..."
# TODO: Replace sleep with health check if desired
sleep 300

# Configure JMeter user.properties for CSV time-series logging
USER_PROPERTIES="/opt/jmeter/bin/user.properties"

echo "🔧 Updating JMeter properties in $USER_PROPERTIES"
# Declare desired properties and their values
declare -A JM_PROPS=(
  [jmeter.save.saveservice.output_format]=csv
  [jmeter.save.saveservice.timestamp_format]=ms
  [jmeter.save.saveservice.time]=true
  [jmeter.save.saveservice.label]=true
  [jmeter.save.saveservice.thread_name]=true
  [jmeter.save.saveservice.response_code]=true
  [jmeter.save.saveservice.successful]=true
  [jmeter.save.saveservice.bytes]=true
  [jmeter.save.saveservice.sent_bytes]=true
  [jmeter.save.saveservice.latency]=true
  [jmeter.save.saveservice.connect_time]=true
  [jmeter.save.saveservice.hostname]=true
  [jmeter.save.saveservice.url]=true
  [jmeter.save.saveservice.idle_time]=true
)

# Iterate and uncomment or set each property
# Iterate to uncomment existing properties or add if missing
for key in "${!JM_PROPS[@]}"; do
  value="${JM_PROPS[$key]}"
  # Uncomment existing property lines
  sed -i "s|^#\s*\(${key}=.*\)|\1|" "$USER_PROPERTIES"
  # If the property isn't present, append it
  if ! grep -q "^${key}=" "$USER_PROPERTIES"; then
    echo "${key}=${value}" >> "$USER_PROPERTIES"
  fi
done

echo "✅ JMeter properties updated."

# Run JMeter tests
echo "🚀 Running JMeter tests..."
echo "🚀 Running JMeter tests..."
jmeter -n -t /app/generate-plan.jmx -l run1.jtl
jmeter -n -t /app/generate-plan.jmx -l run2.jtl
jmeter -n -t /app/generate-plan.jmx -l run3.jtl

# Keep container alive
tail -f /dev/null
